image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - docker-compose build

stages:
  - tests


tests:
  stage: tests
  script:
    - sudo docker-compose run --rm api npm run test

