version: "3.5"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: /app
        NODE_ENV: test
    depends_on:
      - postgresql
    command: npm test
    ports:
       - "3000:3000"
    volumes:
      - .:/app:z
      - /app/node_modules/
    env_file: .env-ci
    networks:
      - backend

  postgresql:
    image: postgres:10.1-alpine
    env_file: .env-ci
    networks:
      - backend
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data:z

networks:
  backend:
      driver: bridge
volumes:
  pgdata: